# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

stages:

- stage: Build
  displayName: Build E-Commerce Platform

  jobs:

  - job: Backend
    displayName: Build Spring Boot Backend

    steps:

    - task: JavaToolInstaller@0
      inputs:
        versionSpec: '17'
        jdkArchitectureOption: 'x64'
        jdkSourceOption: 'PreInstalled'

    - task: Maven@4
      displayName: Maven Package
      inputs:
        mavenPomFile: 'ecommerce-angular-spring/backend/pom.xml'
        goals: 'clean package -DskipTests'

    - task: PublishPipelineArtifact@1
      displayName: Publish Backend Artifact
      inputs:
        targetPath: 'ecommerce-angular-spring/backend/target'
        artifact: 'backend-artifact'

  - job: Frontend
    displayName: Build Angular Frontend

    steps:

    - task: NodeTool@0
      inputs:
        versionSpec: '18.x'

    - script: |
        cd ecommerce-angular-spring/frontend
        npm install
        npm run build
      displayName: Build Angular Application

    - task: PublishPipelineArtifact@1
      displayName: Publish Frontend Artifact
      inputs:
        targetPath: 'ecommerce-angular-spring/frontend/dist/angular-ecommerce/browser'
        artifact: 'frontend-artifact'


- stage: Docker
  displayName: Build and Push Docker Images
  dependsOn: Build

  jobs:

  - job: DockerBackend
    displayName: Docker Backend

    steps:

    - task: DownloadPipelineArtifact@2
      displayName: Download Backend Artifact
      inputs:
        artifact: 'backend-artifact'
        path: '$(Pipeline.Workspace)/backend'

    - script: |
        ls -R $(Pipeline.Workspace)/backend
      displayName: Verify Backend Artifact

  - job: DockerFrontend
    displayName: Docker Frontend

    steps:

    - task: DownloadPipelineArtifact@2
      displayName: Download Frontend Artifact
      inputs:
        artifact: 'frontend-artifact'
        path: '$(Pipeline.Workspace)/frontend'

    - script: |
        ls -R $(Pipeline.Workspace)/frontend
      displayName: Verify Frontend Artifact