# CI pipeline with artifact publishing - backup checkpoint
# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

stages:

- stage: Build
  displayName: Build E-Commerce Platform

  jobs:

  - job: Backend
    displayName: Build Spring Boot Backend

    steps:

    - task: JavaToolInstaller@0
      inputs:
        versionSpec: '17'
        jdkArchitectureOption: 'x64'
        jdkSourceOption: 'PreInstalled'

    - task: Maven@4
      displayName: Maven Package
      inputs:
        mavenPomFile: 'ecommerce-angular-spring/backend/pom.xml'
        goals: 'clean package -DskipTests'

    - task: PublishPipelineArtifact@1
      displayName: Publish Backend Artifact
      inputs:
        targetPath: 'ecommerce-angular-spring/backend/target'
        artifact: 'backend-artifact'

  - job: Frontend
    displayName: Build Angular Frontend

    steps:

    - task: NodeTool@0
      inputs:
        versionSpec: '18.x'

    - script: |
        cd ecommerce-angular-spring/frontend
        npm install
        npm run build
      displayName: Build Angular Application

    - task: PublishPipelineArtifact@1
      displayName: Publish Frontend Artifact
      inputs:
        targetPath: 'ecommerce-angular-spring/frontend/dist/angular-ecommerce/browser'
        artifact: 'frontend-artifact'


- stage: Docker
  displayName: Build and Push Docker Images
  dependsOn: Build

  jobs:

  - job: DockerBackend
    displayName: Docker Backend

    steps:

    - task: DownloadPipelineArtifact@2
      displayName: Download Backend Artifact
      inputs:
        artifact: 'backend-artifact'
        path: '$(Pipeline.Workspace)/backend'

    - script: |
        ls -R $(Pipeline.Workspace)/backend
      displayName: Verify Backend Artifact

    - script: |
        mkdir -p ecommerce-angular-spring/backend/target
        cp $(Pipeline.Workspace)/backend/shop-0.0.1-SNAPSHOT.jar ecommerce-angular-spring/backend/target/
         ls -R ecommerce-angular-spring/backend/target
      displayName: Prepare Backend Docker Context

    - task: Docker@2
      displayName: Build and Push Backend Image
      inputs:
        containerRegistry: 'sc-acr-ecommerce-prod'
        repository: 'ecommerce-backend'
        command: 'buildAndPush'
        Dockerfile: 'ecommerce-angular-spring/backend/Dockerfile'
        buildContext: 'ecommerce-angular-spring/backend'
        tags: |
          latest

  - job: DockerFrontend
    displayName: Docker Frontend

    steps:

    - task: DownloadPipelineArtifact@2
      displayName: Download Frontend Artifact
      inputs:
        artifact: 'frontend-artifact'
        path: '$(Pipeline.Workspace)/frontend'

    - script: |
        ls -R $(Pipeline.Workspace)/frontend
      displayName: Verify Frontend Artifact

    - script: |
        mkdir -p ecommerce-angular-spring/frontend/dist/angular-ecommerce/browser
        cp -R $(Pipeline.Workspace)/frontend/* ecommerce-angular-spring/frontend/dist/angular-ecommerce/browser/
        ls -R ecommerce-angular-spring/frontend/dist/angular-ecommerce/browser
      displayName: Prepare Frontend Docker Context

    - task: Docker@2
      displayName: Build and Push Frontend Image
      inputs:
        containerRegistry: 'sc-acr-ecommerce-prod'
        repository: 'ecommerce-frontend'
        command: 'buildAndPush'
        Dockerfile: 'ecommerce-angular-spring/frontend/Dockerfile'
        buildContext: 'ecommerce-angular-spring/frontend'
        tags: |
          latest 